### ISSUE TITLE
webpack bundle using file path not relative path

### ISSUE THREAD

**Issue by andrewjamesford** [mrsum/webpack-svgstore-plugin#60]
I have an issue specifically with version 2.1.3 when using Webpack-svgstore-plugin in my webpack build I'm getting a file path added to the bundle.js outputted like this:
```
document.addEventListener('DOMContentLoaded', svgXHR('c:/Code/Atmos/z-sample/Sample.ERP/node_modules/images/sprite.99d025b6a647b56d1279b790e94fe0fb.svg', '//localhost:81'), false);
```

I'm puzzled why it adds "c:/Code/Atmos/z-sample/Sample.ERP/node_modules" and is not a relative path to the output. This works in a previous version (2.1.2) until I updated the package to 2.1.3.

The sprite is placed in the correct relative folder of "wwwroot/images" in the file system. But of course my SVG is unreachable via the path supplied in the bundle.js to the svgXHR function, returning a 404 in the browser. 

Here is my webpack.config.js: 
```
var LiveReloadPlugin = require('webpack-livereload-plugin');
var SvgStore = require('webpack-svgstore-plugin');
var path = require('path');
var sourcePath = path.join('App');
var distPath = path.join('wwwroot');

module.exports = {
		entry: {
			app: './App/app.tsx'
		},

		output: {
			path: './wwwroot/',
			filename: '/js/bundle.js'
		},

		resolve: {
			extensions: ['', '.js', '.ts', '.tsx', '.svg']
		},

		devtool: 'source-map',

		plugins: [
			new LiveReloadPlugin(),
			new SvgStore(
				path.join(sourcePath, 'Images', 'icons', '*.svg'),
				'images',
				{
					name: 'sprite.[hash].svg',
					chunk: 'app',
					baseUrl: '//localhost:81',
					svgoOptions: {
					}
				})
		],

		tslint: {
			emitErrors: true,
			failOnHint: false
		},

		module: {
			preLoaders: [
				{
					test: /\.ts(x?)$/,
					loader: "tslint"
				}
			],
			loaders: [
				{
					test: /\.ts(x?)$/,
					loader: 'awesome-typescript-loader'
				},
				{
					test: /\.scss$/,
					loader: 'style!css?sourceMap!sass?sourceMap'
				}
			]
		}
};
```

**Comment by lgordey** [comment]
@andrewjamesford Hi!
Yes, we know about this broken version. Working on it.

Can you, please, make some demo repo with this?

**Comment by andrewjamesford** [comment]
@lgordey here is a simple demo project I made https://github.com/andrewjamesford/webpacksvgstoredemo

**Comment by chicoxyzzy** [comment]
would be great to add test case to prevent future regressions

**Comment by lgordey** [comment]
@fr-ench Please, try fixed plugin version from branch - https://github.com/lgordey/webpack-svgstore-plugin/tree/feature/fix-paths-bug

**Comment by paulcoyle** [comment]
@lgordey I've tried the features/fix-paths-bug branch and I am getting the asset placed under the destination directory with the absolute path nested within it.  This is also occurring with 2.1.13 (not sure about previous versions).

For example, if the destination is set to `/home/paul/project/build`, the path to the output SVG is `/home/paul/project/build/home/paul/project/build/sprites.svg`.

The config for this is as follows:
```javascript
new SvgStorePlugin(
  path.join(__dirname, 'src', 'svg', '*.svg'),
  path.join(__dirname, 'build'),
  {
    name: 'sprites.svg',
    chunk: 'app',
    prefix: 'sprite-'
  }
)
```

**Comment by lgordey** [comment]
@paulcoyle @andrewjamesford Hello!
2.1.4 plugin version should fix this.

@chicoxyzzy 
I really hope to do this in the near future.
With your another opened issues :smile:

**Comment by paulcoyle** [comment]
@lgordey sorry, I am still getting the full, absolute path nested into the output directory as above.

**Comment by lgordey** [comment]
If we test on @andrewjamesford demo with 2 fixes: 
 - change version in package json to `2.1.4`
 - fix source path like `path.join('images', 'icons', '*.svg')`

everything will work correct.

Because now he has `path.join('App', 'images', 'icons', '*.svg')` but `App` folder doesn't include `images` folder - and it was the mistake in config.

@paulcoyle So can you please make a little demo with this?
Maybe it is smth like previous config problem.

**Comment by lgordey** [comment]
I hope the problem goes away, but if not - write here
